server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/amazonwh
    username: amazonwh
    password: amazonwh123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: c2VjdXJlLXNlY3JldC1rZXktZm9yLWFtYXpvbndoLXdtcy1hcHBsaWNhdGlvbi0yMDI0
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
